"""Post output finalization — formats deliverables for clients."""
from typing import Dict
def build_post_text_file(post_data: Dict, business_name: str,
                          niche: str, order_id: str, platform: str) -> str:
    tags = post_data.get("tags", [])
    tags_str = ", ".join(tags) if isinstance(tags, list) else tags
    return f"""═══════════════════════════════════════════════
SMMA POST BUILD — CLIENT DELIVERABLE
═══════════════════════════════════════════════
Order ID  : {order_id}
Business  : {business_name}
Niche     : {niche}
Platform  : {platform.capitalize()}
Best Time : {post_data.get('best_time_to_post', 'N/A')}
Est. Reach: {post_data.get('estimated_reach', 'N/A')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 CAPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{post_data.get('caption', '')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏷️ HASHTAGS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{post_data.get('hashtags', '')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📖 DESCRIPTION (Bio / Google Business)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{post_data.get('description', '')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 CALL TO ACTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{post_data.get('cta', '')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎨 IMAGE PROMPT (Midjourney / DALL-E)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{post_data.get('image_prompt', '')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔖 TAGS / KEYWORDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{tags_str}
    ═══════════════════════════════════════════════
    Generated by SMMA Bot | Deliver to client 🚀
    ═══════════════════════════════════════════════
    """
def build_template_package_text_file(posts: list, business_name: str, niche: str,
                                     order_id: str, platform: str, template_code: str) -> str:
    lines = []
    lines.append("═══════════════════════════════════════════════")
    lines.append(f"SMMA BULK DELIVERABLE — APPROVED TEMPLATE {template_code}")
    lines.append("═══════════════════════════════════════════════")
    lines.append(f"Order ID  : {order_id}")
    lines.append(f"Business  : {business_name}")
    lines.append(f"Niche     : {niche}")
    lines.append(f"Platform  : {platform.capitalize()}")
    lines.append("")
    for i, post in enumerate(posts):
        lines.append(f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        lines.append(f"📝 POST #{i+1} ({post.get('style', 'POST').upper()})")
        lines.append(f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        lines.append(f"Best Time : {post.get('best_time', 'N/A')}")
        lines.append(f"Expected  : {post.get('expected_improvement', 'N/A')}")
        lines.append("")
        lines.append("📝 CAPTION:")
        lines.append(post.get('caption', ''))
        lines.append("")
        lines.append("🏷️ HASHTAGS:")
        lines.append(post.get('hashtags', ''))
        lines.append("")
        lines.append("🎨 IMAGE/VIDEO PROMPT:")
        lines.append(post.get('image_prompt', ''))
        lines.append("")
        lines.append("💡 WHY BETTER:")
        lines.append(post.get('why_better', ''))
        lines.append("\n" + "="*45 + "\n")
    lines.append("═══════════════════════════════════════════════")
    lines.append("Generated by SMMA Bot | Deliver to client 🚀")
    lines.append("═══════════════════════════════════════════════")
    return "\n".join(lines)
def format_post_embed_fields(post_data: Dict) -> Dict[str, str]:
    tags = post_data.get("tags", [])
    tags_str = ", ".join(tags) if isinstance(tags, list) else tags
    return {
        "best_time": post_data.get("best_time_to_post", "N/A"),
        "caption": post_data.get("caption", "")[:1000],
        "hashtags": post_data.get("hashtags", "")[:500],
        "description": post_data.get("description", "")[:400],
        "cta": post_data.get("cta", ""),
        "estimated_reach": post_data.get("estimated_reach", "N/A"),
        "tags": tags_str[:200] or "—",
        "image_prompt": post_data.get("image_prompt", "")[:300],
    }
def build_analysis_report_text_file(analysis: dict, post_data: dict, business_name: str, niche: str) -> str:
    lines = []
    lines.append("═══════════════════════════════════════════════")
    lines.append(f"SMMA AUDIT REPORT & CONTENT STRATEGY: {business_name.upper()}")
    lines.append("═══════════════════════════════════════════════")
    lines.append(f"Target URL: {analysis.get('url', '')}")
    lines.append(f"Niche     : {niche}")
    lines.append(f"SSL Secure: {'Yes' if analysis.get('is_secure') else 'No'}")
    lines.append(f"Load Time : {analysis.get('load_time_ms', 0)}ms")
    lines.append(f"Tech Stack: {', '.join(analysis.get('tech_stack', [])) or 'None detected'}")
    lines.append(f"Weakness Score: {analysis.get('weakness_score', 0)}/10")
    lines.append("")
    
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("⚠️ DETECTED ISSUES & WEAK POINTS")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    probs = analysis.get("problems", [])
    if probs:
        for p in probs:
            lines.append(f"❌ {p}")
    else:
        lines.append("✅ No major issues detected.")
    lines.append("")
    
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("🧠 WHY CURRENT POSTS AREN'T WORKING")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(post_data.get("post_analysis", "No analysis available."))
    lines.append("")
    
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("📌 5 IMPROVED POST TEMPLATES")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    
    for i, tpl in enumerate(post_data.get("templates", [])):
        lines.append(f"\n--- TEMPLATE {i+1}: {tpl.get('style', 'Post').upper()} ---")
        lines.append(f"File Type : {tpl.get('file_type', 'PNG')}")
        lines.append(f"Best Time : {tpl.get('best_time', 'N/A')}")
        lines.append(f"Expected  : {tpl.get('expected_improvement', 'N/A')}")
        lines.append("")
        lines.append("📝 CAPTION:")
        lines.append(tpl.get('caption', ''))
        lines.append("")
        lines.append("🏷️ HASHTAGS:")
        lines.append(tpl.get('hashtags', ''))
        lines.append("")
        lines.append("🖼️ VISUAL PROMPT / COPY ON IMAGE:")
        lines.append(tpl.get('image_prompt', ''))
        lines.append("")
        lines.append("💡 WHY THIS IS BETTER:")
        lines.append(tpl.get('why_better', ''))
        lines.append("-" * 40)
        
    lines.append("\n═══════════════════════════════════════════════")
    lines.append("Generated by SMMA Bot | Ready for delivery 🚀")
    lines.append("═══════════════════════════════════════════════")
    return "\n".join(lines)
